#%RAML 1.0 NamedExample

[
  {
  "id" : "12345",
  "name": "abc",
  "phonenumber":
  [
  07456567857,
  07456967857
  ]
  },
  {
  "id" : "12345",
  "name": "abc",
  "phonenumber": 0756789999
  },
  {
  "id" : "55555",
  "name": "frc",
  "phonenumber": 0123459999
  },
  {
  "id" : "99345",
  "name": "rtc",
  "phonenumber": 06543999
  },
]